# Generated by Django 3.2 on 2021-05-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
